/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 04:26:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Dual Access Control | Secure Login</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Fonts & Icons -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #2b5876;\r\n");
      out.write("            --secondary-color: #4e4376;\r\n");
      out.write("            --admin-color: #8E2DE2;\r\n");
      out.write("            --user-color: #00B4DB;\r\n");
      out.write("            --error-color: #f72585;\r\n");
      out.write("            --light-color: #f8f9fa;\r\n");
      out.write("            --dark-color: #212529;\r\n");
      out.write("            --border-radius: 8px;\r\n");
      out.write("            --box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            --transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            color: var(--dark-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .split-container { display: flex; width: 100%; height: 100vh; }\r\n");
      out.write("\r\n");
      out.write("        .left-side {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),\r\n");
      out.write("                        url('images/background.jpg') center/cover no-repeat;\r\n");
      out.write("            color: white;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .left-content { max-width: 500px; }\r\n");
      out.write("\r\n");
      out.write("        .security-badge {\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .left-side h1 { font-size: 2.5rem; margin-bottom: 1rem; }\r\n");
      out.write("        .left-side p { font-size: 1.1rem; opacity: 0.9; }\r\n");
      out.write("\r\n");
      out.write("        .security-feature {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .security-feature i {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            color: var(--user-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .right-side {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-toggle {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: var(--box-shadow);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-btn {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-btn.active {\r\n");
      out.write("            background: linear-gradient(to right, var(--admin-color), var(--user-color));\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-btn:not(.active) {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #6c757d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-btn:first-child {\r\n");
      out.write("            border-right: 1px solid #e9ecef;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-message { margin-bottom: 2rem; }\r\n");
      out.write("        .welcome-message h2 { color: var(--primary-color); }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            background: linear-gradient(to right, var(--admin-color), var(--user-color));\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            color: var(--error-color);\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forgot-password, .register-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forgot-password a, .register-link a {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .forgot-password a:hover, .register-link a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .split-container { flex-direction: column; }\r\n");
      out.write("            .left-side { text-align: center; padding: 2rem; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"split-container\">\r\n");
      out.write("        <div class=\"left-side\">\r\n");
      out.write("            <div class=\"left-content\">\r\n");
      out.write("                <div class=\"security-badge\">\r\n");
      out.write("                    <i class=\"fas fa-shield-alt\"></i> Dual Access Control System\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1>Secure Authentication Portal</h1>\r\n");
      out.write("                <p>Dual-level access for administrators and standard users.</p>\r\n");
      out.write("                <div class=\"security-feature\">\r\n");
      out.write("                    <i class=\"fas fa-user-shield\"></i> Role-based Access Control\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"security-feature\">\r\n");
      out.write("                    <i class=\"fas fa-lock\"></i> AES File Encryption\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"security-feature\">\r\n");
      out.write("                    <i class=\"fas fa-database\"></i> Cloud-Hosted Security\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"right-side\">\r\n");
      out.write("            <div class=\"login-container\">\r\n");
      out.write("                <div class=\"access-toggle\">\r\n");
      out.write("                    <div class=\"access-btn active\" id=\"adminBtn\"><i class=\"fas fa-user-cog\"></i> Admin</div>\r\n");
      out.write("                    <div class=\"access-btn\" id=\"userBtn\"><i class=\"fas fa-user\"></i> User</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"welcome-message\">\r\n");
      out.write("                    <h2>Admin Login</h2>\r\n");
      out.write("                    <p>Secure credentials required</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"LoginServlet\" method=\"POST\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"role\" value=\"admin\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"username\">Username</label>\r\n");
      out.write("                        <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"Enter your username\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\">Password</label>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn\">Log In</button>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                ");
 String errorMessage = (String) request.getAttribute("errorMessage");
                   if (errorMessage != null) {
                
      out.write("\r\n");
      out.write("                    <p class=\"error\">");
      out.print( errorMessage );
      out.write("</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"forgot-password\">\r\n");
      out.write("                    <a href=\"#\">Forgot password?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"register-link\">\r\n");
      out.write("                    Don't have an account? <a href=\"register.jsp\">Register here</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"adminBtn\").addEventListener(\"click\", function () {\r\n");
      out.write("            this.classList.add(\"active\");\r\n");
      out.write("            document.getElementById(\"userBtn\").classList.remove(\"active\");\r\n");
      out.write("            document.querySelector(\"input[name='role']\").value = \"admin\";\r\n");
      out.write("            document.querySelector(\".welcome-message h2\").textContent = \"Admin Login\";\r\n");
      out.write("            document.querySelector(\".welcome-message p\").textContent = \"Secure credentials required\";\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"userBtn\").addEventListener(\"click\", function () {\r\n");
      out.write("            this.classList.add(\"active\");\r\n");
      out.write("            document.getElementById(\"adminBtn\").classList.remove(\"active\");\r\n");
      out.write("            document.querySelector(\"input[name='role']\").value = \"user\";\r\n");
      out.write("            document.querySelector(\".welcome-message h2\").textContent = \"User Login\";\r\n");
      out.write("            document.querySelector(\".welcome-message p\").textContent = \"Access your files securely\";\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
