/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 05:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String message = (String) request.getAttribute("message");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Create Account</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #4F46E5;\r\n");
      out.write("            --primary-light: #EEF2FF;\r\n");
      out.write("            --text: #111827;\r\n");
      out.write("            --text-light: #6B7280;\r\n");
      out.write("            --border: #E5E7EB;\r\n");
      out.write("            --success: #10B981;\r\n");
      out.write("            --error: #EF4444;\r\n");
      out.write("            --radius: 8px;\r\n");
      out.write("            --transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            background-color: #F9FAFB;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-wrapper {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 420px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-header h1 {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-header p {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-form {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 32px;\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field i {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 14px;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input, select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 16px 12px 42px;\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        select {\r\n");
      out.write("            appearance: none;\r\n");
      out.write("            background-image: url(\"data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: right 14px center;\r\n");
      out.write("            background-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .role-select {\r\n");
      out.write("            background-image: url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"%236B7280\"><path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z\"/></svg>'), \r\n");
      out.write("                            url(\"data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e\");\r\n");
      out.write("            background-position: left 14px center, right 14px center;\r\n");
      out.write("            background-size: 16px, 16px;\r\n");
      out.write("            padding-left: 42px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus, select:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: var(--primary);\r\n");
      out.write("            box-shadow: 0 0 0 3px var(--primary-light);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 14px;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background: #4338CA;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message {\r\n");
      out.write("            padding: 14px;\r\n");
      out.write("            border-radius: var(--radius);\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message.success {\r\n");
      out.write("            background: rgba(16, 185, 129, 0.1);\r\n");
      out.write("            color: var(--success);\r\n");
      out.write("            border: 1px solid rgba(16, 185, 129, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message.error {\r\n");
      out.write("            background: rgba(239, 68, 68, 0.1);\r\n");
      out.write("            color: var(--error);\r\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-prompt {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 24px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-prompt a {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-prompt a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .spinner {\r\n");
      out.write("            display: none;\r\n");
      out.write("            margin: 16px auto;\r\n");
      out.write("            border: 3px solid rgba(79, 70, 229, 0.1);\r\n");
      out.write("            border-top: 3px solid var(--primary);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            width: 24px;\r\n");
      out.write("            height: 24px;\r\n");
      out.write("            animation: spin 1s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            0% { transform: rotate(0deg); }\r\n");
      out.write("            100% { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .register-form {\r\n");
      out.write("                padding: 24px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .register-header h1 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"register-wrapper\">\r\n");
      out.write("        <div class=\"register-header\">\r\n");
      out.write("            <h1>Get Started</h1>\r\n");
      out.write("            <p>Create your account in just a minute</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"register-form\">\r\n");
      out.write("            <form action=\"RegisterServlet\" method=\"post\" onsubmit=\"showSpinner()\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"username\">Username</label>\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Password</label>\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Create a password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"role\">Account Type</label>\r\n");
      out.write("                    <select id=\"role\" name=\"role\" class=\"role-select\" required>\r\n");
      out.write("                        <option value=\"\" disabled selected>Select your role</option>\r\n");
      out.write("                        <option value=\"user\">Standard User</option>\r\n");
      out.write("                        <option value=\"admin\">Administrator</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"department\">Department</label>\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <i class=\"fas fa-building\"></i>\r\n");
      out.write("                        <input type=\"text\" id=\"department\" name=\"department\" placeholder=\"e.g. IT, Marketing\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn\">\r\n");
      out.write("                    <i class=\"fas fa-user-plus\"></i> Create Account\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"spinner\" id=\"spinner\"></div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (message != null) { 
      out.write("\r\n");
      out.write("                <div class=\"message ");
      out.print( message.toLowerCase().contains("success") ? "success" : "error" );
      out.write("\">\r\n");
      out.write("                    <i class=\"fas ");
      out.print( message.toLowerCase().contains("success") ? "fa-check-circle" : "fa-exclamation-circle" );
      out.write("\"></i>\r\n");
      out.write("                    ");
      out.print( message );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"login-prompt\">\r\n");
      out.write("                Already have an account? <a href=\"index.jsp\">Sign in</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function showSpinner() {\r\n");
      out.write("            document.getElementById(\"spinner\").style.display = \"block\";\r\n");
      out.write("            document.querySelector('button[type=\"submit\"]').disabled = true;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Add real-time password validation if needed\r\n");
      out.write("        const passwordInput = document.getElementById('password');\r\n");
      out.write("        passwordInput.addEventListener('input', function() {\r\n");
      out.write("            // Password strength validation logic can go here\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
