/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 04:43:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.dualaccess.db.DBConnection;

public final class upload_005flog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    if (session == null || session.getAttribute("username") == null || 
        !"admin".equalsIgnoreCase((String)session.getAttribute("role"))) {
        response.sendRedirect("index.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Upload Log</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url(\"images/background.jpg\");\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container-bg {\r\n");
      out.write("            background-color: rgba(255,255,255,0.95);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h3 {\r\n");
      out.write("            color: #28a745;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchInput {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container container-bg\">\r\n");
      out.write("    <h3>Upload Log</h3>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("        <input type=\"text\" class=\"form-control me-3\" id=\"searchInput\" placeholder=\"Search by username or filename\" />\r\n");
      out.write("        <button class=\"btn btn-primary\" onclick=\"downloadCSV()\">Export CSV</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <table class=\"table table-bordered table-hover\" id=\"logTable\">\r\n");
      out.write("        <thead class=\"table-success\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>#</th>\r\n");
      out.write("                <th>Username</th>\r\n");
      out.write("                <th>Filename</th>\r\n");
      out.write("                <th>Upload Time</th>\r\n");
      out.write("                <th>Action</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");

            try (Connection conn = DBConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement("SELECT * FROM upload_log ORDER BY upload_time DESC");
                 ResultSet rs = ps.executeQuery()) {

                int count = 1;
                while (rs.next()) {
        
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( count++ );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getString("username") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getString("filename") );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( rs.getTimestamp("upload_time") );
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <form method=\"post\" action=\"DeleteUploadLogServlet\" onsubmit=\"return confirm('Delete this log?');\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"logId\" value=\"");
      out.print( rs.getInt("id") );
      out.write("\" />\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm btn-danger\">Delete</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        ");

                }
            } catch (Exception e) {
                out.println("<tr><td colspan='5' class='text-danger'>Error: " + e.getMessage() + "</td></tr>");
            }
        
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"text-center mt-4\">\r\n");
      out.write("        <a href=\"welcome.jsp\" class=\"btn btn-secondary\">Back to Dashboard</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('searchInput').addEventListener('input', function () {\r\n");
      out.write("        let filter = this.value.toLowerCase();\r\n");
      out.write("        let rows = document.querySelectorAll('#logTable tbody tr');\r\n");
      out.write("        rows.forEach(row => {\r\n");
      out.write("            let text = row.textContent.toLowerCase();\r\n");
      out.write("            row.style.display = text.includes(filter) ? '' : 'none';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function downloadCSV() {\r\n");
      out.write("        let rows = document.querySelectorAll('#logTable tr');\r\n");
      out.write("        let csv = Array.from(rows).map(row => \r\n");
      out.write("            Array.from(row.querySelectorAll('td, th'))\r\n");
      out.write("                 .map(cell => `\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cell.innerText}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"`).join(',')\r\n");
      out.write("        ).join('\\n');\r\n");
      out.write("\r\n");
      out.write("        let blob = new Blob([csv], { type: 'text/csv' });\r\n");
      out.write("        let url = URL.createObjectURL(blob);\r\n");
      out.write("        let a = document.createElement('a');\r\n");
      out.write("        a.href = url;\r\n");
      out.write("        a.download = 'upload_log.csv';\r\n");
      out.write("        document.body.appendChild(a);\r\n");
      out.write("        a.click();\r\n");
      out.write("        document.body.removeChild(a);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
