/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 08:08:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Enhanced session validation
    if (session == null || session.getAttribute("username") == null) {
        response.sendRedirect("index.jsp?redirect=upload.jsp");
        return;
    }

    String username = (String) session.getAttribute("username");
    String message = (String) request.getAttribute("message");
    String fileType = (String) request.getAttribute("fileType");
    String fileSize = (String) request.getAttribute("fileSize");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Upload File | Secure Storage</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #4e73df;\r\n");
      out.write("            --success-color: #1cc88a;\r\n");
      out.write("            --danger-color: #e74a3b;\r\n");
      out.write("            --warning-color: #f6c23e;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Nunito', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #f8f9fc 0%, #e9ecef 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .upload-card {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 69, 0.15);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-body {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-upload-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-upload-input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 46px;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-upload-label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            border: 2px dashed #d1d3e2;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-upload-label:hover {\r\n");
      out.write("            border-color: var(--primary-color);\r\n");
      out.write("            background-color: rgba(78, 115, 223, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-upload-label i {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-info {\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("            padding: 0.75rem;\r\n");
      out.write("            background-color: #f8f9fc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-info.active {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-meta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-top: 0.5rem;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: #6c757d;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-upload {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 0.75rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-upload:hover {\r\n");
      out.write("            background-color: #2e59d9;\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-upload:disabled {\r\n");
      out.write("            background-color: #b7c1e0;\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #loader {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("            display: none;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .spinner {\r\n");
      out.write("            width: 3rem;\r\n");
      out.write("            height: 3rem;\r\n");
      out.write("            border: 0.25rem solid rgba(78, 115, 223, 0.2);\r\n");
      out.write("            border-top-color: var(--primary-color);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: spin 1s linear infinite;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            0% { transform: rotate(0deg); }\r\n");
      out.write("            100% { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert-message {\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert-message.show {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-link a {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-link a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .progress {\r\n");
      out.write("            height: 8px;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .progress-bar {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            transition: width 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Loading Overlay -->\r\n");
      out.write("    <div id=\"loader\">\r\n");
      out.write("        <div class=\"spinner\"></div>\r\n");
      out.write("        <h4>Uploading your file...</h4>\r\n");
      out.write("        <p class=\"text-muted\">Please wait while we process your file</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"upload-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h2><i class=\"bi bi-cloud-arrow-up\"></i> Upload File</h2>\r\n");
      out.write("            <p class=\"mb-0\">Welcome, ");
      out.print( username );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <form id=\"uploadForm\" action=\"UploadServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <div class=\"file-upload-wrapper\">\r\n");
      out.write("                    <input type=\"file\" name=\"file\" id=\"fileInput\" class=\"file-upload-input\" required>\r\n");
      out.write("                    <label for=\"fileInput\" class=\"file-upload-label\">\r\n");
      out.write("                        <i class=\"bi bi-file-earmark-arrow-up\"></i>\r\n");
      out.write("                        <span id=\"dropText\">Choose a file or drag it here</span>\r\n");
      out.write("                        <div class=\"file-meta\" id=\"fileMeta\"></div>\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"file-info\" id=\"fileInfo\">\r\n");
      out.write("                    <strong>Selected File:</strong> <span id=\"fileName\"></span>\r\n");
      out.write("                    <div class=\"file-meta\">\r\n");
      out.write("                        <span id=\"fileTypeDisplay\">Type: Not specified</span>\r\n");
      out.write("                        <span id=\"fileSizeDisplay\">Size: 0 KB</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"progress\" id=\"progressBar\">\r\n");
      out.write("                    <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 0%\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-upload w-100\" id=\"uploadBtn\" enable>\r\n");
      out.write("                    <i class=\"bi bi-upload\"></i> Upload File\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("            ");
 if (message != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert-message show alert ");
      out.print( message.toLowerCase().contains("success") ? "alert-success" : "alert-danger" );
      out.write("\">\r\n");
      out.write("                    <i class=\"bi ");
      out.print( message.toLowerCase().contains("success") ? "bi-check-circle" : "bi-exclamation-triangle" );
      out.write("\"></i>\r\n");
      out.write("                    ");
      out.print( message );
      out.write("\r\n");
      out.write("                    ");
 if (fileType != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"file-meta mt-2\">\r\n");
      out.write("                            <span>Type: ");
      out.print( fileType );
      out.write("</span>\r\n");
      out.write("                            ");
 if (fileSize != null) { 
      out.write("\r\n");
      out.write("                                <span>Size: ");
      out.print( fileSize );
      out.write("</span>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"back-link\">\r\n");
      out.write("                <a href=\"welcome.jsp\"><i class=\"bi bi-arrow-left\"></i> Back to Dashboard</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // File input handling\r\n");
      out.write("        const fileInput = document.getElementById('fileInput');\r\n");
      out.write("        const fileName = document.getElementById('fileName');\r\n");
      out.write("        const fileInfo = document.getElementById('fileInfo');\r\n");
      out.write("        const fileTypeDisplay = document.getElementById('fileTypeDisplay');\r\n");
      out.write("        const fileSizeDisplay = document.getElementById('fileSizeDisplay');\r\n");
      out.write("        const uploadBtn = document.getElementById('uploadBtn');\r\n");
      out.write("        const dropText = document.getElementById('dropText');\r\n");
      out.write("        const progressBar = document.getElementById('progressBar');\r\n");
      out.write("        const progressBarInner = document.querySelector('.progress-bar');\r\n");
      out.write("        \r\n");
      out.write("        // Drag and drop functionality\r\n");
      out.write("        const uploadLabel = document.querySelector('.file-upload-label');\r\n");
      out.write("        \r\n");
      out.write("        uploadLabel.addEventListener('dragover', (e) => {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            uploadLabel.style.borderColor = 'var(--primary-color)';\r\n");
      out.write("            uploadLabel.style.backgroundColor = 'rgba(78, 115, 223, 0.1)';\r\n");
      out.write("            dropText.textContent = 'Drop file to upload';\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        uploadLabel.addEventListener('dragleave', () => {\r\n");
      out.write("            uploadLabel.style.borderColor = '#d1d3e2';\r\n");
      out.write("           ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
