/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 08:11:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_005flogs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // ✅ Only admin access allowed
    if (session == null || session.getAttribute("username") == null || !"admin".equals(session.getAttribute("role"))) {
        response.sendRedirect("index.jsp?unauthorized=true");
        return;
    }

    String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Log Monitoring | Admin Panel</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .card-hover:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .admin-header {\r\n");
      out.write("            background: linear-gradient(135deg, #2c3e50, #4ca1af);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("    <!-- 🔐 Top Admin Navigation Bar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark admin-header mb-4\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"welcome.jsp\">\r\n");
      out.write("                <i class=\"bi bi-shield-lock\"></i> SecureAccess Admin\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"d-flex align-items-center ms-auto\">\r\n");
      out.write("                <span class=\"text-white me-3\"><i class=\"bi bi-person-circle\"></i> ");
      out.print( username );
      out.write("</span>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn btn-outline-light btn-sm\">\r\n");
      out.write("                    <i class=\"bi bi-box-arrow-right\"></i> Logout\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- 📊 Log Monitoring Dashboard -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"mb-4 d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <h2><i class=\"bi bi-clipboard2-data\"></i> Log Monitoring</h2>\r\n");
      out.write("            <a href=\"welcome.jsp\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("                <i class=\"bi bi-arrow-left\"></i> Back to Dashboard\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <!-- Upload Logs -->\r\n");
      out.write("            <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                <div class=\"card card-hover h-100\">\r\n");
      out.write("                    <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("                        <h5 class=\"mb-0\"><i class=\"bi bi-upload\"></i> Upload Logs</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>View detailed upload history including usernames, files, and timestamps.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer bg-transparent\">\r\n");
      out.write("                        <a href=\"upload_log_display.jsp\" class=\"btn btn-primary w-100\"><i class=\"bi bi-eye\"></i> View Upload Logs</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Download Logs -->\r\n");
      out.write("            <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                <div class=\"card card-hover h-100\">\r\n");
      out.write("                    <div class=\"card-header bg-success text-white\">\r\n");
      out.write("                        <h5 class=\"mb-0\"><i class=\"bi bi-download\"></i> Download Logs</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <p>Audit all download events to track data access and user behavior.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-footer bg-transparent\">\r\n");
      out.write("                        <a href=\"download_log_display.jsp\" class=\"btn btn-success w-100\"><i class=\"bi bi-eye\"></i> View Download Logs</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 📈 Quick Stats -->\r\n");
      out.write("        <div class=\"row mt-5\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <div class=\"card shadow-sm\">\r\n");
      out.write("                    <div class=\"card-header bg-info text-white\">\r\n");
      out.write("                        <h5 class=\"mb-0\"><i class=\"bi bi-speedometer2\"></i> Quick Statistics</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body text-center row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <h4 class=\"text-primary\">1,248</h4>\r\n");
      out.write("                            <p>Total Uploads</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <h4 class=\"text-success\">3,742</h4>\r\n");
      out.write("                            <p>Total Downloads</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <h4 class=\"text-warning\">42</h4>\r\n");
      out.write("                            <p>Active Users</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ Bootstrap Bundle -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
