/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2025-05-12 14:14:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    if (session == null || session.getAttribute("username") == null) {
        response.sendRedirect("index.jsp");
        return;
    }
    String username = (String) session.getAttribute("username");
    String role = (String) session.getAttribute("role");
    String department = (String) session.getAttribute("department");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Dashboard | ");
      out.print( username );
      out.write("</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #4361ee;\r\n");
      out.write("            --primary-light: #ebf0ff;\r\n");
      out.write("            --secondary: #3f37c9;\r\n");
      out.write("            --success: #4cc9f0;\r\n");
      out.write("            --danger: #f72585;\r\n");
      out.write("            --dark: #1a1a1a;\r\n");
      out.write("            --light: #f8f9fa;\r\n");
      out.write("            --gray: #6c757d;\r\n");
      out.write("            --border-radius: 10px;\r\n");
      out.write("            --shadow: 0 4px 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            --transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            background-color: #f5f7fa;\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 280px 1fr;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar Styles */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: var(--shadow);\r\n");
      out.write("            padding: 2rem 1.5rem;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .brand {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("            padding-bottom: 1.5rem;\r\n");
      out.write("            border-bottom: 1px solid rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .brand-icon {\r\n");
      out.write("            width: 36px;\r\n");
      out.write("            height: 36px;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .brand-name {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-profile {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .avatar {\r\n");
      out.write("            width: 48px;\r\n");
      out.write("            height: 48px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border: 3px solid ");
      out.print( "admin".equalsIgnoreCase(role) ? "var(--primary)" : "var(--success)" );
      out.write(";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-info {\r\n");
      out.write("            line-height: 1.4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-name {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-role {\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("            background: ");
      out.print( "admin".equalsIgnoreCase(role) ? "var(--primary-light)" : "#e6f7ff" );
      out.write(";\r\n");
      out.write("            padding: 2px 8px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-item:hover, .nav-item.active {\r\n");
      out.write("            background: var(--primary-light);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-item i {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content Styles */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            padding: 2rem 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title h1 {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title p {\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            color: var(--danger);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Dashboard Cards */\r\n");
      out.write("        .card-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            box-shadow: var(--shadow);\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-icon {\r\n");
      out.write("            width: 48px;\r\n");
      out.write("            height: 48px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-icon.primary {\r\n");
      out.write("            background: var(--primary-light);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-icon.success {\r\n");
      out.write("            background: #e6f7ff;\r\n");
      out.write("            color: var(--success);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-icon.danger {\r\n");
      out.write("            background: #ffebf1;\r\n");
      out.write("            color: var(--danger);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-desc {\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 6px;\r\n");
      out.write("            padding: 0.5rem 1rem;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-btn:hover {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Recent Activity */\r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-list {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            box-shadow: var(--shadow);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 1rem 1.5rem;\r\n");
      out.write("            border-bottom: 1px solid rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-item:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-icon {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-right: 1rem;\r\n");
      out.write("            background: var(--primary-light);\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-details {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-title {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            margin-bottom: 0.25rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .activity-time {\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Styles */\r\n");
      out.write("        @media (max-width: 992px) {\r\n");
      out.write("            .dashboard-container {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .sidebar {\r\n");
      out.write("                height: auto;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .main-content {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .card-grid {\r\n");
      out.write("                grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .header {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: flex-start;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .card-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        <!-- Sidebar Navigation -->\r\n");
      out.write("        <aside class=\"sidebar\">\r\n");
      out.write("            <div class=\"brand\">\r\n");
      out.write("                <div class=\"brand-icon\">\r\n");
      out.write("                    <i class=\"bi bi-shield-lock\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"brand-name\">SecureAccess</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"user-profile\">\r\n");
      out.write("                <img src=\"images/profile.png\" class=\"avatar\" alt=\"");
      out.print( username );
      out.write("\">\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                    <div class=\"user-name\">");
      out.print( username );
      out.write("</div>\r\n");
      out.write("                    <div class=\"user-role\">");
      out.print( role );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <nav class=\"nav-menu\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-item active\">\r\n");
      out.write("                    <i class=\"bi bi-speedometer2\"></i>\r\n");
      out.write("                    Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"download.jsp\" class=\"nav-item\">\r\n");
      out.write("                    <i class=\"bi bi-download\"></i>\r\n");
      out.write("                    Download Files\r\n");
      out.write("                </a>\r\n");
      out.write("                ");
 if ("admin".equalsIgnoreCase(role)) { 
      out.write("\r\n");
      out.write("                    <a href=\"upload.jsp\" class=\"nav-item\">\r\n");
      out.write("                        <i class=\"bi bi-cloud-upload\"></i>\r\n");
      out.write("                        Upload Files\r\n");
      out.write("                    </a>\r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </nav>\r\n");
      out.write("        </aside>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Main Content Area -->\r\n");
      out.write("        <main class=\"main-content\">\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                <div class=\"page-title\">\r\n");
      out.write("                    <h1>Dashboard</h1>\r\n");
      out.write("                    <p>Welcome back, ");
      out.print( username );
      out.write("! Here's what's happening today.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"logout-btn\">\r\n");
      out.write("                    <i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("                    Logout\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Quick Actions Cards -->\r\n");
      out.write("            <div class=\"card-grid\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-icon success\">\r\n");
      out.write("                        <i class=\"bi bi-download\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"card-title\">Download Files</h3>\r\n");
      out.write("                    <p class=\"card-desc\">Access all available files in the secure repository</p>\r\n");
      out.write("                    <a href=\"download.jsp\" class=\"card-btn\">\r\n");
      out.write("                        Go to Downloads\r\n");
      out.write("                        <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if ("admin".equalsIgnoreCase(role)) { 
      out.write("\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-icon primary\">\r\n");
      out.write("                            <i class=\"bi bi-cloud-upload\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"card-title\">Upload Files</h3>\r\n");
      out.write("                        <p class=\"card-desc\">Add new files to the secure repository</p>\r\n");
      out.write("                        <a href=\"upload.jsp\" class=\"card-btn\">\r\n");
      out.write("                            Upload Now\r\n");
      out.write("                            <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("       \r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Recent Activity Section -->\r\n");
      out.write("            <h3 class=\"section-title\">Recent Activity</h3>\r\n");
      out.write("            <div class=\"activity-list\">\r\n");
      out.write("                <div class=\"activity-item\">\r\n");
      out.write("                    <div class=\"activity-icon\">\r\n");
      out.write("                        <i class=\"bi bi-download\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"activity-details\">\r\n");
      out.write("                        <div class=\"activity-title\">File downloaded: Quarterly_Report.pdf</div>\r\n");
      out.write("                        <div class=\"activity-time\">Today, 10:45 AM</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"activity-item\">\r\n");
      out.write("                    <div class=\"activity-icon\">\r\n");
      out.write("                        <i class=\"bi bi-person-check\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"activity-details\">\r\n");
      out.write("                        <div class=\"activity-title\">Successful login from Chrome on Windows</div>\r\n");
      out.write("                        <div class=\"activity-time\">Today, 10:30 AM</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 if ("admin".equalsIgnoreCase(role)) { 
      out.write("\r\n");
      out.write("                    <div class=\"activity-item\">\r\n");
      out.write("                        <div class=\"activity-icon\">\r\n");
      out.write("                            <i class=\"bi bi-cloud-upload\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"activity-details\">\r\n");
      out.write("                            <div class=\"activity-title\">File uploaded: Project_Proposal.docx</div>\r\n");
      out.write("                            <div class=\"activity-time\">Yesterday, 4:22 PM</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <div class=\"activity-item\">\r\n");
      out.write("                    <div class=\"activity-icon\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"activity-details\">\r\n");
      out.write("                        <div class=\"activity-title\">Password changed successfully</div>\r\n");
      out.write("                        <div class=\"activity-time\">2 days ago</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
